# Generated by Django 5.2.11 on 2026-02-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('OrderID', models.IntegerField()),
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField()),
                ('ItemName', models.CharField(max_length=100)),
                ('OrderQty', models.IntegerField()),
                ('UnitPrice', models.FloatField(max_length=20)),
                ('TotalAmount', models.FloatField(max_length=20)),
                ('Adress', models.CharField(max_length=100)),
            ],
        ),
    ]
